[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.virtualenv']

[phases.install]
cmds = [
    'python -m venv /opt/venv',
    '. /opt/venv/bin/activate && pip install --upgrade pip',
    '. /opt/venv/bin/activate && pip install -r backend/requirements.txt'
]

[start]
cmd = '. /opt/venv/bin/activate && bash backend/start.sh'
