"""Add optimized composite indexes

Revision ID: 232cc545ff37
Revises: 7dfb4597f6c4
Create Date: 2025-10-26 23:56:40.091298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232cc545ff37'
down_revision: Union[str, None] = '7dfb4597f6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversaciones_contexto_usuario_id'), 'conversaciones_contexto', ['usuario_id'], unique=False)
    op.create_index('ix_conversaciones_usuario_timestamp_desc', 'conversaciones_contexto', ['usuario_id', 'timestamp'], unique=False)
    op.create_index('ix_correlaciones_usuario_fecha', 'correlaciones', ['usuario_id', 'fecha_calculo'], unique=False)
    op.create_index(op.f('ix_correlaciones_usuario_id'), 'correlaciones', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_estados_animo_usuario_id'), 'estados_animo', ['usuario_id'], unique=False)
    op.create_index('ix_estados_animo_usuario_timestamp', 'estados_animo', ['usuario_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_feedback_respuestas_usuario_id'), 'feedback_respuestas', ['usuario_id'], unique=False)
    op.create_index('ix_feedback_usuario_rating', 'feedback_respuestas', ['usuario_id', 'utilidad_rating'], unique=False)
    op.create_index('ix_feedback_usuario_timestamp', 'feedback_respuestas', ['usuario_id', 'timestamp'], unique=False)
    op.create_index('ix_habitos_usuario_activo', 'habitos', ['usuario_id', 'activo'], unique=False)
    op.create_index(op.f('ix_habitos_usuario_id'), 'habitos', ['usuario_id'], unique=False)
    op.create_index('ix_habitos_usuario_nombre', 'habitos', ['usuario_id', 'nombre_habito'], unique=False)
    op.create_index(op.f('ix_registros_habitos_habito_id'), 'registros_habitos', ['habito_id'], unique=False)
    op.create_index('ix_registros_habitos_habito_timestamp', 'registros_habitos', ['habito_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_registros_habitos_usuario_id'), 'registros_habitos', ['usuario_id'], unique=False)
    op.create_index('ix_registros_habitos_usuario_timestamp', 'registros_habitos', ['usuario_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_resumenes_conversacion_usuario_id'), 'resumenes_conversacion', ['usuario_id'], unique=False)
    op.create_index('ix_resumenes_usuario_fecha', 'resumenes_conversacion', ['usuario_id', 'fecha_resumen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resumenes_usuario_fecha', table_name='resumenes_conversacion')
    op.drop_index(op.f('ix_resumenes_conversacion_usuario_id'), table_name='resumenes_conversacion')
    op.drop_index('ix_registros_habitos_usuario_timestamp', table_name='registros_habitos')
    op.drop_index(op.f('ix_registros_habitos_usuario_id'), table_name='registros_habitos')
    op.drop_index('ix_registros_habitos_habito_timestamp', table_name='registros_habitos')
    op.drop_index(op.f('ix_registros_habitos_habito_id'), table_name='registros_habitos')
    op.drop_index('ix_habitos_usuario_nombre', table_name='habitos')
    op.drop_index(op.f('ix_habitos_usuario_id'), table_name='habitos')
    op.drop_index('ix_habitos_usuario_activo', table_name='habitos')
    op.drop_index('ix_feedback_usuario_timestamp', table_name='feedback_respuestas')
    op.drop_index('ix_feedback_usuario_rating', table_name='feedback_respuestas')
    op.drop_index(op.f('ix_feedback_respuestas_usuario_id'), table_name='feedback_respuestas')
    op.drop_index('ix_estados_animo_usuario_timestamp', table_name='estados_animo')
    op.drop_index(op.f('ix_estados_animo_usuario_id'), table_name='estados_animo')
    op.drop_index(op.f('ix_correlaciones_usuario_id'), table_name='correlaciones')
    op.drop_index('ix_correlaciones_usuario_fecha', table_name='correlaciones')
    op.drop_index('ix_conversaciones_usuario_timestamp_desc', table_name='conversaciones_contexto')
    op.drop_index(op.f('ix_conversaciones_contexto_usuario_id'), table_name='conversaciones_contexto')
    # ### end Alembic commands ###
