"""Initial database schema

Revision ID: 7dfb4597f6c4
Revises: 
Create Date: 2025-10-26 23:52:51.432620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfb4597f6c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('preferencias_conversacionales', sa.Text(), nullable=True),
    sa.Column('temas_sensibles', sa.Text(), nullable=True),
    sa.Column('patrones_lenguaje_favoritos', sa.Text(), nullable=True),
    sa.Column('historial_temas_recurrentes', sa.Text(), nullable=True),
    sa.Column('emociones_primarias_frecuentes', sa.Text(), nullable=True),
    sa.Column('valores_principales', sa.Text(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_perfil_usuario_id'), 'perfil_usuario', ['id'], unique=False)
    op.create_table('respuestas_exitosas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('patron_pregunta', sa.String(), nullable=False),
    sa.Column('respuesta_efectiva', sa.Text(), nullable=False),
    sa.Column('veces_usado', sa.Integer(), nullable=True),
    sa.Column('utilidad_promedio', sa.Float(), nullable=True),
    sa.Column('fecha_descubierta', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_uso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respuestas_exitosas_id'), 'respuestas_exitosas', ['id'], unique=False)
    op.create_table('resumenes_conversacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_resumen', sa.DateTime(), nullable=True),
    sa.Column('resumen_texto', sa.Text(), nullable=False),
    sa.Column('temas_principales', sa.Text(), nullable=True),
    sa.Column('emociones_detectadas', sa.Text(), nullable=True),
    sa.Column('progreso_emocional', sa.Text(), nullable=True),
    sa.Column('num_mensajes', sa.Integer(), nullable=True),
    sa.Column('periodo_inicio', sa.DateTime(), nullable=True),
    sa.Column('periodo_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumenes_conversacion_fecha_resumen'), 'resumenes_conversacion', ['fecha_resumen'], unique=False)
    op.create_index(op.f('ix_resumenes_conversacion_id'), 'resumenes_conversacion', ['id'], unique=False)
    op.create_table('feedback_respuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=True),
    sa.Column('mensaje_usuario', sa.Text(), nullable=False),
    sa.Column('respuesta_loki', sa.Text(), nullable=False),
    sa.Column('utilidad_rating', sa.Integer(), nullable=True),
    sa.Column('ayudo', sa.Boolean(), nullable=True),
    sa.Column('notas_feedback', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones_contexto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_respuestas_id'), 'feedback_respuestas', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_respuestas_timestamp'), 'feedback_respuestas', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_respuestas_timestamp'), table_name='feedback_respuestas')
    op.drop_index(op.f('ix_feedback_respuestas_id'), table_name='feedback_respuestas')
    op.drop_table('feedback_respuestas')
    op.drop_index(op.f('ix_resumenes_conversacion_id'), table_name='resumenes_conversacion')
    op.drop_index(op.f('ix_resumenes_conversacion_fecha_resumen'), table_name='resumenes_conversacion')
    op.drop_table('resumenes_conversacion')
    op.drop_index(op.f('ix_respuestas_exitosas_id'), table_name='respuestas_exitosas')
    op.drop_table('respuestas_exitosas')
    op.drop_index(op.f('ix_perfil_usuario_id'), table_name='perfil_usuario')
    op.drop_table('perfil_usuario')
    # ### end Alembic commands ###
