"""Initial database schema

Revision ID: 7dfb4597f6c4
Revises: 
Create Date: 2025-10-26 23:52:51.432620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfb4597f6c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('nivel_CMV', sa.String(), nullable=True),
    sa.Column('preferencias_tracking', sa.Text(), nullable=True),
    sa.Column('frecuencia_checkins', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('nivel_confianza', sa.Integer(), nullable=True),
    sa.Column('total_interacciones', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estados_animo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('notas_texto', sa.Text(), nullable=True),
    sa.Column('contexto_extraido', sa.Text(), nullable=True),
    sa.Column('disparadores_detectados', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_habito', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('objetivo_semanal', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversaciones_contexto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('mensaje_usuario', sa.Text(), nullable=False),
    sa.Column('respuesta_loki', sa.Text(), nullable=True),
    sa.Column('entidades_extraidas', sa.Text(), nullable=True),
    sa.Column('categorias_detectadas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correlaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.String(), nullable=False),
    sa.Column('impacto_animo', sa.Float(), nullable=False),
    sa.Column('confianza_estadistica', sa.Float(), nullable=False),
    sa.Column('num_datos', sa.Integer(), nullable=True),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_habitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('habito_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['habito_id'], ['habitos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfil_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('preferencias_conversacionales', sa.Text(), nullable=True),
    sa.Column('temas_sensibles', sa.Text(), nullable=True),
    sa.Column('patrones_lenguaje_favoritos', sa.Text(), nullable=True),
    sa.Column('historial_temas_recurrentes', sa.Text(), nullable=True),
    sa.Column('emociones_primarias_frecuentes', sa.Text(), nullable=True),
    sa.Column('valores_principales', sa.Text(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_perfil_usuario_id'), 'perfil_usuario', ['id'], unique=False)

    # Add optimized composite indexes
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=False)
    op.create_index('ix_usuarios_telefono', 'usuarios', ['telefono'], unique=True)
    op.create_index(op.f('ix_conversaciones_contexto_id'), 'conversaciones_contexto', ['id'], unique=False)
    op.create_index(op.f('ix_conversaciones_contexto_usuario_id'), 'conversaciones_contexto', ['usuario_id'], unique=False)
    op.create_index('ix_conversaciones_usuario_timestamp_desc', 'conversaciones_contexto', ['usuario_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_conversaciones_contexto_timestamp'), 'conversaciones_contexto', ['timestamp'], unique=False)
    op.create_index(op.f('ix_correlaciones_id'), 'correlaciones', ['id'], unique=False)
    op.create_index('ix_correlaciones_usuario_fecha', 'correlaciones', ['usuario_id', 'fecha_calculo'], unique=False)
    op.create_index(op.f('ix_correlaciones_usuario_id'), 'correlaciones', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_estados_animo_id'), 'estados_animo', ['id'], unique=False)
    op.create_index(op.f('ix_estados_animo_usuario_id'), 'estados_animo', ['usuario_id'], unique=False)
    op.create_index('ix_estados_animo_usuario_timestamp', 'estados_animo', ['usuario_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_estados_animo_timestamp'), 'estados_animo', ['timestamp'], unique=False)
    op.create_index(op.f('ix_habitos_id'), 'habitos', ['id'], unique=False)
    op.create_index('ix_habitos_usuario_activo', 'habitos', ['usuario_id', 'activo'], unique=False)
    op.create_index(op.f('ix_habitos_usuario_id'), 'habitos', ['usuario_id'], unique=False)
    op.create_index('ix_habitos_usuario_nombre', 'habitos', ['usuario_id', 'nombre_habito'], unique=False)
    op.create_index(op.f('ix_registros_habitos_id'), 'registros_habitos', ['id'], unique=False)
    op.create_index(op.f('ix_registros_habitos_timestamp'), 'registros_habitos', ['timestamp'], unique=False)
    op.create_index(op.f('ix_registros_habitos_habito_id'), 'registros_habitos', ['habito_id'], unique=False)
    op.create_index('ix_registros_habitos_habito_timestamp', 'registros_habitos', ['habito_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_registros_habitos_usuario_id'), 'registros_habitos', ['usuario_id'], unique=False)
    op.create_index('ix_registros_habitos_usuario_timestamp', 'registros_habitos', ['usuario_id', 'timestamp'], unique=False)

    op.create_table('respuestas_exitosas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('patron_pregunta', sa.String(), nullable=False),
    sa.Column('respuesta_efectiva', sa.Text(), nullable=False),
    sa.Column('veces_usado', sa.Integer(), nullable=True),
    sa.Column('utilidad_promedio', sa.Float(), nullable=True),
    sa.Column('fecha_descubierta', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_uso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respuestas_exitosas_id'), 'respuestas_exitosas', ['id'], unique=False)
    op.create_table('resumenes_conversacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_resumen', sa.DateTime(), nullable=True),
    sa.Column('resumen_texto', sa.Text(), nullable=False),
    sa.Column('temas_principales', sa.Text(), nullable=True),
    sa.Column('emociones_detectadas', sa.Text(), nullable=True),
    sa.Column('progreso_emocional', sa.Text(), nullable=True),
    sa.Column('num_mensajes', sa.Integer(), nullable=True),
    sa.Column('periodo_inicio', sa.DateTime(), nullable=True),
    sa.Column('periodo_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumenes_conversacion_fecha_resumen'), 'resumenes_conversacion', ['fecha_resumen'], unique=False)
    op.create_index(op.f('ix_resumenes_conversacion_id'), 'resumenes_conversacion', ['id'], unique=False)
    op.create_index(op.f('ix_resumenes_conversacion_usuario_id'), 'resumenes_conversacion', ['usuario_id'], unique=False)
    op.create_index('ix_resumenes_usuario_fecha', 'resumenes_conversacion', ['usuario_id', 'fecha_resumen'], unique=False)

    op.create_table('feedback_respuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=True),
    sa.Column('mensaje_usuario', sa.Text(), nullable=False),
    sa.Column('respuesta_loki', sa.Text(), nullable=False),
    sa.Column('utilidad_rating', sa.Integer(), nullable=True),
    sa.Column('ayudo', sa.Boolean(), nullable=True),
    sa.Column('notas_feedback', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversaciones_contexto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_respuestas_id'), 'feedback_respuestas', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_respuestas_timestamp'), 'feedback_respuestas', ['timestamp'], unique=False)
    op.create_index(op.f('ix_feedback_respuestas_usuario_id'), 'feedback_respuestas', ['usuario_id'], unique=False)
    op.create_index('ix_feedback_usuario_rating', 'feedback_respuestas', ['usuario_id', 'utilidad_rating'], unique=False)
    op.create_index('ix_feedback_usuario_timestamp', 'feedback_respuestas', ['usuario_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_usuario_timestamp', table_name='feedback_respuestas')
    op.drop_index('ix_feedback_usuario_rating', table_name='feedback_respuestas')
    op.drop_index(op.f('ix_feedback_respuestas_usuario_id'), table_name='feedback_respuestas')
    op.drop_index(op.f('ix_feedback_respuestas_timestamp'), table_name='feedback_respuestas')
    op.drop_index(op.f('ix_feedback_respuestas_id'), table_name='feedback_respuestas')
    op.drop_table('feedback_respuestas')
    op.drop_index('ix_resumenes_usuario_fecha', table_name='resumenes_conversacion')
    op.drop_index(op.f('ix_resumenes_conversacion_usuario_id'), table_name='resumenes_conversacion')
    op.drop_index(op.f('ix_resumenes_conversacion_id'), table_name='resumenes_conversacion')
    op.drop_index(op.f('ix_resumenes_conversacion_fecha_resumen'), table_name='resumenes_conversacion')
    op.drop_table('resumenes_conversacion')
    op.drop_index(op.f('ix_respuestas_exitosas_id'), table_name='respuestas_exitosas')
    op.drop_table('respuestas_exitosas')
    op.drop_index(op.f('ix_perfil_usuario_id'), table_name='perfil_usuario')
    op.drop_table('perfil_usuario')
    op.drop_index('ix_registros_habitos_usuario_timestamp', table_name='registros_habitos')
    op.drop_index(op.f('ix_registros_habitos_usuario_id'), table_name='registros_habitos')
    op.drop_index('ix_registros_habitos_habito_timestamp', table_name='registros_habitos')
    op.drop_index(op.f('ix_registros_habitos_habito_id'), table_name='registros_habitos')
    op.drop_index(op.f('ix_registros_habitos_timestamp'), table_name='registros_habitos')
    op.drop_index(op.f('ix_registros_habitos_id'), table_name='registros_habitos')
    op.drop_table('registros_habitos')
    op.drop_index('ix_habitos_usuario_nombre', table_name='habitos')
    op.drop_index(op.f('ix_habitos_usuario_id'), table_name='habitos')
    op.drop_index('ix_habitos_usuario_activo', table_name='habitos')
    op.drop_index(op.f('ix_habitos_id'), table_name='habitos')
    op.drop_table('habitos')
    op.drop_index(op.f('ix_estados_animo_timestamp'), table_name='estados_animo')
    op.drop_index('ix_estados_animo_usuario_timestamp', table_name='estados_animo')
    op.drop_index(op.f('ix_estados_animo_usuario_id'), table_name='estados_animo')
    op.drop_index(op.f('ix_estados_animo_id'), table_name='estados_animo')
    op.drop_table('estados_animo')
    op.drop_index(op.f('ix_correlaciones_usuario_id'), table_name='correlaciones')
    op.drop_index('ix_correlaciones_usuario_fecha', table_name='correlaciones')
    op.drop_index(op.f('ix_correlaciones_id'), table_name='correlaciones')
    op.drop_table('correlaciones')
    op.drop_index(op.f('ix_conversaciones_contexto_timestamp'), table_name='conversaciones_contexto')
    op.drop_index('ix_conversaciones_usuario_timestamp_desc', table_name='conversaciones_contexto')
    op.drop_index(op.f('ix_conversaciones_contexto_usuario_id'), table_name='conversaciones_contexto')
    op.drop_index(op.f('ix_conversaciones_contexto_id'), table_name='conversaciones_contexto')
    op.drop_table('conversaciones_contexto')
    op.drop_index('ix_usuarios_telefono', table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
